//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace LitRes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LitRes.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О ПРИЛОЖЕНИИ.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас возникли вопросы, пожелания.
        /// </summary>
        public static string AboutSupportLine1 {
            get {
                return ResourceManager.GetString("AboutSupportLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или технические проблемы,.
        /// </summary>
        public static string AboutSupportLine2 {
            get {
                return ResourceManager.GetString("AboutSupportLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to напишите нам на .
        /// </summary>
        public static string AboutSupportLine3 {
            get {
                return ResourceManager.GetString("AboutSupportLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛитРес – это первое приложение для чтения и покупки русскоязычных электронных книг, специально разработанное для Windows Phone. Скачав приложение, вы получаете доступ к полному каталогу русскоязычных книг ЛитРес, включая современную прозу, фэнтези и фантастику, детективы, деловую литературу и многое другое..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        public static string AppVersionText {
            get {
                return ResourceManager.GetString("AppVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не хочу регистрироваться.
        /// </summary>
        public static string DoNotRegisterButtonText {
            get {
                return ResourceManager.GetString("DoNotRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединяйтесь к нам на .
        /// </summary>
        public static string FacebookText {
            get {
                return ResourceManager.GetString("FacebookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginButtonText2 {
            get {
                return ResourceManager.GetString("LoginButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ознакомьтесь с .
        /// </summary>
        public static string OfferText {
            get {
                return ResourceManager.GetString("OfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterButtonText2 {
            get {
                return ResourceManager.GetString("RegisterButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка на ЛитРес.
        /// </summary>
        public static string RegistrationMessageBoxCaption {
            get {
                return ResourceManager.GetString("RegistrationMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надежно хранить все купленные
        ///книги. Все ваши покупки будут
        ///находиться не только на устройстве,
        ///но и в сетевом хранилище..
        /// </summary>
        public static string RegistrationMessageBoxHelpText1 {
            get {
                return ResourceManager.GetString("RegistrationMessageBoxHelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать и управлять списками чтения
        ///на всех ваших устройствах - книги,
        ///купленные на одном устройстве,
        ///будут доступны на всех остальных..
        /// </summary>
        public static string RegistrationMessageBoxHelpText2 {
            get {
                return ResourceManager.GetString("RegistrationMessageBoxHelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читая одну книгу с разных устройств,
        ///вам больше не придется заботиться
        ///о том, где вы закончили читать.
        ///На другом устройстве вы начнете
        ///читать с того же места..
        /// </summary>
        public static string RegistrationMessageBoxHelpText3 {
            get {
                return ResourceManager.GetString("RegistrationMessageBoxHelpText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы совершаете покупку в магазине ЛитРес.
        ///Для вашего удобства предлагаем завести
        ///аккаунт ЛитРес, который позволит вам:.
        /// </summary>
        public static string RegistrationMessageBoxMessage {
            get {
                return ResourceManager.GetString("RegistrationMessageBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
